### ISSUE TITLE
Homepage url in Cargo.toml is wrong

### ISSUE THREAD

**Issue by jhoobergs** [derekdreery/dvi-rs#1]
See https://github.com/derekdreery/dvi-rs/blob/master/Cargo.toml#L8
The link to this github repo from docs.rs is not working: https://docs.rs/dvi/0.1.0/dvi

**Comment by richard-uk1** [comment]
I've updated the homepage and made it the repository (since that's what it is in reality).

Version `2.1` has the correct link.
